version: 4.0.0-build{build} 
image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
    - /^feature\/.$/
    - /^release\/.$/
    - /^(.*\/)?ci-.*$/
clone_depth: 1
before_build:
  - ps: |
      dotnet --version
      dotnet restore
build_script:
  - ps: |
      dotnet build -c Release
      dotnet pack -c Release -o .\artifacts
test_script:
  - ps: |
      dotnet test      
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/wangkanai/api/v2/package
  api_key:
    secure: YY8jIrOCrsuVBg/iqwS2jVwZ462EWKFMZ+95fBEDqM1DiH0H2w7OMgUx3rQ3XTzl
  artifact: /.*\.nupkg/
  on:
    branch: main